services:
  hiveserver2:
    image: apache/hive:4.1.0
    container_name: hive_server2
    environment:
      SERVICE_NAME: hiveserver2
    ports:
      - "10000:10000"   # puerto JDBC Hive2
      - "10002:10002"   # puerto UI/Web de HiveServer2
    volumes:
      - warehouse:/opt/hive/data/warehouse

volumes:
  warehouse: