services:
  sql_server1:
    image: mcr.microsoft.com/mssql/server:2025-latest
    container_name: sql_server1
    environment:
      MSSQL_SA_PASSWORD: "@Dmin123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql_data1:/var/opt/mssql

  sql_server2:
    depends_on:
      - sql_server1
    image: mcr.microsoft.com/mssql/server:2025-latest
    container_name: sql_server2
    environment:
      MSSQL_SA_PASSWORD: "@Dmin123"
      ACCEPT_EULA: "Y"
    ports:
      - "1434:1433"
    volumes:
      - sql_data2:/var/opt/mssql

volumes:
  sql_data1:
  sql_data2: